advert_index:
    path:     /{page}
    defaults:
        _controller: AppBundle:Advert:index
        page:        1
    requirements:
        page: \d*

advert_show:
    path:     /show/{id}
    defaults: { _controller: "AppBundle:Advert:show" }
    requirements:
        id: \d+

advert_new:
    path:     /new
    defaults: { _controller: "AppBundle:Advert:new" }

advert_edit:
    path:     /edit/{id}
    defaults: { _controller: "AppBundle:Advert:edit" }
    requirements:
        id: \d+

advert_delete:
    path:     /delete/{id}
    defaults: { _controller: "AppBundle:Advert:delete" }
    requirements:
        id: \d+
