services:
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - name: kernel.event_subscriber

    app.advert_manager:
        class: AppBundle\Manager\AppManager
        arguments:
            - "@doctrine.orm.entity_manager"